version: 2
updates:
- package-ecosystem: nuget
  directories:
    - "src/"
    - "src/Tests/"
  schedule:
    interval: daily
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: weekly
